name: heroes-queue-discord-bot

services:
  queue-bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/core

